language: cpp
sudo: required
git:
  depth: 3
env: PYTHONPATH=$PYTHONPATH:/usr/local/cmake-3.9.2/bin/
cache:
  directories:
    - release
    - blockscipy/build
    - .mtime_cache
    - $HOME/.local
    - $HOME/.cache/pip
matrix:
  include:
    - stage: Build C++ Library
      dist: xenial
      before_install: .travis/build_ubuntu_cpp.sh
      script: .travis/compile_ubuntu_cpp.sh
    - stage: Build Python Module
      dist: xenial
      before_install:
        - .travis/build_ubuntu_cpp.sh
        - .travis/build_ubuntu_python.sh
      script:
        - .travis/compile_ubuntu_cpp.sh
        - .travis/compile_ubuntu_python.sh

